#!/usr/bin/env python3
"""
system5_engine.py — System 5 Pentachoron Engine
Models 4 concurrent threads over a 60-step cycle with BRIDGE mode detection
from 5 interlocking tetrahedral cells.
"""

from itertools import permutations, combinations
from math import factorial
from collections import Counter


def sign(p):
    n = len(p)
    inversions = sum(1 for i in range(n) for j in range(i+1, n) if p[i] > p[j])
    return 1 if inversions % 2 == 0 else -1


# ═══════════════════════════════════════════════════════════════════
# Build A_5 and choose a canonical ordering
# ═══════════════════════════════════════════════════════════════════
A5_elements = sorted([p for p in permutations(range(5)) if sign(p) == 1])
e = tuple(range(5))  # identity

# We need a 60-step cycle. Use a generator of A_5 to produce a Hamiltonian path
# through the Cayley graph. A_5 is generated by a = (0,1,2,3,4) [5-cycle] and
# b = (0,1)(2,3) [double transposition].

def compose(p, q):
    """Compose permutations: (p∘q)(i) = p(q(i))"""
    return tuple(p[q[i]] for i in range(len(p)))

def inverse(p):
    n = len(p)
    inv = [0]*n
    for i in range(n):
        inv[p[i]] = i
    return tuple(inv)

# Generator: 5-cycle
gen5 = (1, 2, 3, 4, 0)  # (01234)
# Generator: double transposition
gen_dt = (1, 0, 3, 2, 4)  # (01)(23)

# Build a Hamiltonian path through A_5 using the Steinhaus-Johnson-Trotter-like approach
# Actually, let's use a simpler approach: generate the cycle via coset decomposition
# A_5 / A_4 has 5 cosets. Within each coset, use the A_4 12-step cycle.

# The 5 cosets of A_4 (fixing element 4) in A_5
# Coset representatives: rotations that move element 4
coset_reps = []
for target in range(5):
    # Find a permutation in A_5 that sends 4 -> target
    for p in A5_elements:
        if p[4] == target:
            coset_reps.append(p)
            break

print("=" * 100)
print("  SYSTEM 5 PENTACHORON ENGINE")
print("=" * 100)

print("\n  Coset representatives (A_5 / A_4):")
for i, rep in enumerate(coset_reps):
    print(f"    Coset {i}: {rep}  (sends 4 -> {rep[4]})")

# ═══════════════════════════════════════════════════════════════════
# Build the 5 tetrahedral cells and their 12-step E/R patterns
# ═══════════════════════════════════════════════════════════════════
# Each cell is obtained by removing one vertex.
# Cell k uses the System 4 pattern on the remaining 4 vertices.

# System 4 E/R pattern per thread (from established results):
# Set A: R R E E E E E E E R R R
# Set B: E R R R R R E E E E E E
# Set C: E E E E E R R R R R E E
sys4_modes_A = list("RREEEEEEERR R")  # will use clean version
sys4_modes = {
    'A': ['R','R','E','E','E','E','E','E','E','R','R','R'],
    'B': ['E','R','R','R','R','R','E','E','E','E','E','E'],
    'C': ['E','E','E','E','E','R','R','R','R','R','E','E'],
}

print("\n" + "─" * 100)
print("  TETRAHEDRAL CELLS AND BRIDGE MODE DETECTION")
print("─" * 100)

# For each of the 60 steps, determine which tetrahedral cells
# are active and what their E/R assignment is.
# 
# The 60-step cycle visits 5 cosets × 12 steps.
# At each step, the current permutation belongs to 4 of the 5 cosets
# of the 5 different A_4 subgroups (one per vertex).

# For each vertex v, A_4^v = {p in A_5 : p(v) = v}
# The coset of p in A_5/A_4^v is determined by p(v).

# Build the 60-step sequence using the 5-cycle generator
# to traverse cosets, and within each coset use A_4's 12-step structure.

# Actually, let's think about this more carefully.
# The 60 steps correspond to the 60 elements of A_5.
# We need a specific ordering (a Hamiltonian cycle in the Cayley graph).
# 
# For our purposes, we'll use the coset decomposition:
# Order the 60 elements as 5 blocks of 12, where each block
# is a coset of A_4 (fixing vertex 4).

# Within each coset, order by the System 4 cycle.
# The System 4 cycle uses terms {1,2,4,5,7,8} with polar pairs [1(8)],[4(5)],[7(2)].

# For the pentachoron, the 10 particular terms form 5 polar pairs
# (one per vertex-opposite-face duality).
# Vertices: a=0, b=1, c=2, d=3, e=4
# Each vertex is opposite to a tetrahedral face.
# Polar pairs: vertex v <-> face opposite to v

# Let's label the 10 terms using the 10 edges of the pentachoron
edges_5 = list(combinations(range(5), 2))
print(f"\n  10 edges (particular terms): {edges_5}")

# Group edges into 5 polar pairs based on vertex-face duality
# For each vertex v, the 4 edges touching v are paired with
# the 4 edges NOT touching v (which form the opposite face's edges)
# But 4 vs 6 doesn't pair evenly...
# 
# Actually: each vertex touches 4 edges, and the opposite face
# has C(4,2)=6 edges. So the pairing is different.
#
# The 5 polar pairs come from the 5 "vertex-opposite-face" dualities.
# In the pentachoron, each vertex v has an opposite face (the cell not containing v).
# The polar pair for vertex v is: {v} <-> {complement of v}.
# But these are vertices, not edges.
#
# Let's use a different approach: the 10 edges split into 5 pairs
# where each pair consists of two non-adjacent edges (they share no vertex).
# In K_5, two edges are non-adjacent iff they form a perfect matching on 4 vertices.
# But K_5 has 5 vertices (odd), so no perfect matching exists!
#
# This is a key difference from System 4 (K_4 has 3 perfect matchings = 3 polar pairs).
# In System 5, the 10 edges cannot be paired into non-adjacent pairs.
# Instead, the pairing is vertex-based: for each vertex v,
# the 4 edges touching v form one "pole" and v itself is the other.

print("\n  Polar structure in the pentachoron:")
print("  Unlike the tetrahedron (where edges pair into 3 polar pairs),")
print("  the pentachoron has 5 vertex-face dualities:")
for v in range(5):
    touching = [e for e in edges_5 if v in e]
    opposite = [e for e in edges_5 if v not in e]
    print(f"    Vertex {v}: touches {len(touching)} edges, opposite face has {len(opposite)} edges")

# ═══════════════════════════════════════════════════════════════════
# Simulate the 60-step cycle with BRIDGE mode detection
# ═══════════════════════════════════════════════════════════════════
print("\n" + "─" * 100)
print("  60-STEP CYCLE SIMULATION")
print("─" * 100)

# For each of the 60 steps, we determine the mode from each of the 5
# tetrahedral cells' perspectives.
# 
# Step i belongs to coset j of A_4^v for each vertex v.
# The position within that coset determines the E/R mode.
#
# We'll use a simplified model:
# - Order the 60 steps as 5 blocks of 12 (cosets of A_4^4, fixing vertex e=4)
# - For each step, determine its position in each of the 5 A_4^v cosets
# - Use the System 4 mode pattern to assign E/R from each cell's perspective
# - If all 4 active cells agree: pure E or pure R
# - If they disagree: BRIDGE mode

# Build A_4 fixing vertex 4
A4_fix4 = sorted([p for p in A5_elements if p[4] == 4])
print(f"  |A_4 fixing vertex 4| = {len(A4_fix4)}")

# Build all 5 copies of A_4
A4_copies = {}
for v in range(5):
    A4_copies[v] = sorted([p for p in A5_elements if p[v] == v])
    
# Order the 60 elements by cosets of A_4^4
# Coset k: elements that send 4 -> k
cosets = {}
for k in range(5):
    cosets[k] = sorted([p for p in A5_elements if p[4] == k])
    print(f"  Coset {k} (4->{k}): {len(cosets[k])} elements")

# For each step (element p), determine its position in each A_4^v
# by finding which coset of A_4^v it belongs to (determined by p(v))
# and its position within that coset.

# Build the mode assignment for each cell at each step
# We'll use a flat ordering: coset 0 steps 0-11, coset 1 steps 12-23, etc.
step_sequence = []
for k in range(5):
    step_sequence.extend(cosets[k])

print(f"\n  Total steps: {len(step_sequence)}")

# For each step, determine the mode from each cell's perspective
# Cell v uses A_4^v. The step's position in A_4^v's coset structure
# determines the mode.

# Simplified: for cell v, the step p belongs to coset p(v) of A_4^v.
# Within that coset, we need the position. For simplicity, we'll use
# the System 4 mode pattern based on the coset index modulo 12.

# Actually, let's use a cleaner model:
# For each cell v, the 60 steps split into 5 blocks of 12 (cosets of A_4^v).
# The System 4 pattern assigns modes within each block of 12.
# The 4 threads of System 5 correspond to the 4 cells that are "active"
# at each step (all cells except the one whose vertex is being "moved").

# For the flat ordering (cosets of A_4^4):
# Cell 4's perspective: steps 0-11 are in A_4^4 itself, steps 12-23 in coset 1, etc.
# Cell 0's perspective: different coset structure.

# Let's compute the mode from each cell's perspective
cell_modes = {}  # cell_modes[v][step_index] = 'E' or 'R'

for v in range(5):
    cell_modes[v] = []
    # Group steps by their coset in A_4^v
    coset_assignment = {}  # step_index -> (coset_of_A4v, position_in_coset)
    coset_members = {}  # coset_label -> [step_indices]
    
    for idx, p in enumerate(step_sequence):
        coset_label = p[v]  # which coset of A_4^v
        if coset_label not in coset_members:
            coset_members[coset_label] = []
        coset_members[coset_label].append(idx)
    
    # For each coset, assign the System 4 12-step mode pattern
    # Use thread A's pattern for simplicity (the "canonical" thread)
    sys4_pattern = sys4_modes['A']  # 12 modes
    
    for coset_label in sorted(coset_members.keys()):
        members = coset_members[coset_label]
        for pos, step_idx in enumerate(members):
            mode = sys4_pattern[pos % 12]
            coset_assignment[step_idx] = mode
    
    # Build the full mode sequence for this cell
    for idx in range(60):
        cell_modes[v].append(coset_assignment.get(idx, '?'))

# Now detect BRIDGE mode
print("\n  Mode analysis per step (first 20 steps):")
print("  ┌──────┬───────┬───────┬───────┬───────┬───────┬──────────┬──────────┐")
print("  │ Step │ Cell0 │ Cell1 │ Cell2 │ Cell3 │ Cell4 │ E-count  │ Mode     │")
print("  ├──────┼───────┼───────┼───────┼───────┼───────┼──────────┼──────────┤")

mode_counts = Counter()
step_modes = []

for idx in range(60):
    modes = [cell_modes[v][idx] for v in range(5)]
    e_count = modes.count('E')
    r_count = modes.count('R')
    
    if e_count == 5:
        mode = 'E (pure)'
    elif r_count == 5:
        mode = 'R (pure)'
    elif e_count >= 4:
        mode = 'E (dom.)'
    elif r_count >= 4:
        mode = 'R (dom.)'
    else:
        mode = 'BRIDGE'
    
    mode_counts[mode] += 1
    step_modes.append(mode)
    
    if idx < 20:
        print(f"  │ {idx+1:>4} │   {modes[0]}   │   {modes[1]}   │   {modes[2]}   │   {modes[3]}   │   {modes[4]}   │ {e_count}E/{r_count}R    │ {mode:<8} │")

print("  └──────┴───────┴───────┴───────┴───────┴───────┴──────────┴──────────┘")
print("  (showing first 20 of 60 steps)")

print("\n  MODE DISTRIBUTION ACROSS 60 STEPS:")
print("  ┌──────────────┬───────┬─────────┐")
print("  │ Mode         │ Count │ Percent │")
print("  ├──────────────┼───────┼─────────┤")
for mode in sorted(mode_counts.keys()):
    pct = mode_counts[mode] / 60 * 100
    print(f"  │ {mode:<12} │ {mode_counts[mode]:>5} │ {pct:>5.1f}%  │")
print("  └──────────────┴───────┴─────────┘")

bridge_count = sum(1 for m in step_modes if 'BRIDGE' in m)
pure_count = sum(1 for m in step_modes if 'pure' in m)
dom_count = sum(1 for m in step_modes if 'dom.' in m)

print(f"""
  Summary:
    Pure E or R:     {pure_count} steps ({pure_count/60*100:.1f}%)
    Dominant E or R: {dom_count} steps ({dom_count/60*100:.1f}%)
    BRIDGE (mixed):  {bridge_count} steps ({bridge_count/60*100:.1f}%)
""")

# ═══════════════════════════════════════════════════════════════════
# Thread perspective: 4 threads phase-locked at 90° (360/4)
# ═══════════════════════════════════════════════════════════════════
print("─" * 100)
print("  4 THREADS PHASE-LOCKED AT 90° (360°/4 = 15 steps)")
print("─" * 100)

# With 4 threads and 60 steps, the phase offset is 60/4 = 15 steps
offset = 15
print(f"  Phase offset: {offset} steps (= 60/4)")
print(f"  Phase angle: {360/4}° = 90°")
print()

# Build thread sequences
# Thread k starts at step k*15
for t in range(4):
    start = t * offset
    thread_modes_list = [step_modes[(start + s) % 60] for s in range(60)]
    e_pure = sum(1 for m in thread_modes_list if 'E' in m and 'pure' in m)
    r_pure = sum(1 for m in thread_modes_list if 'R' in m and 'pure' in m)
    bridge = sum(1 for m in thread_modes_list if 'BRIDGE' in m)
    e_dom = sum(1 for m in thread_modes_list if 'E' in m and 'dom.' in m)
    r_dom = sum(1 for m in thread_modes_list if 'R' in m and 'dom.' in m)
    print(f"  Thread {chr(65+t)} (offset {start:>2}): "
          f"pure_E={e_pure}, dom_E={e_dom}, BRIDGE={bridge}, dom_R={r_dom}, pure_R={r_pure}")

# ═══════════════════════════════════════════════════════════════════
# The E/R/B ternary mode
# ═══════════════════════════════════════════════════════════════════
print("\n" + "─" * 100)
print("  THE E/R/B TERNARY MODE SYSTEM")
print("─" * 100)

print("""
  System 5 introduces a TERNARY mode classification:
  
  ┌──────────┬────────────┬──────────────┬──────────────────────────────┐
  │ Mode     │ Symbol     │ Condition    │ Cognitive Meaning            │
  ├──────────┼────────────┼──────────────┼──────────────────────────────┤
  │ Pure E   │ E          │ All cells E  │ Fully forward / actual       │
  │ Pure R   │ R          │ All cells R  │ Fully backward / virtual     │
  │ BRIDGE   │ B (or E⊕R) │ Cells mixed  │ Simultaneous E+R = CREATIVE │
  └──────────┴────────────┴──────────────┴──────────────────────────────┘
  
  In System 4: each step is binary (E or R).
  In System 5: each step is ternary (E, R, or B).
  
  The BRIDGE mode is NOT a third independent orientation.
  It is the SUPERPOSITION of E and R — the point where
  forward and backward inference become indistinguishable.
  
  This is structurally forced by A_5's simplicity:
  - A_4 can separate threads from interfaces (V_4 is normal)
  - A_5 CANNOT separate them (no normal subgroups)
  - Therefore, E/R assignments from different cells MUST conflict
  - The conflict IS the BRIDGE mode
  
  ╔═══════════════════════════════════════════════════════════════════╗
  ║  BRIDGE = CREATIVITY = the structural impossibility of          ║
  ║  separating perception from imagination at the level of A_5.    ║
  ║                                                                   ║
  ║  This is why Campbell calls System 5 "Creativity":              ║
  ║  it is the first system where E and R MUST co-occur.            ║
  ╚═══════════════════════════════════════════════════════════════════╝
""")
